### ISSUE TITLE
S3 Bucket Takeovers - False Negatives 

### ISSUE THREAD

**Issue by lstatro** [projectdiscovery/nuclei-templates#10318]
The  [S3 bucket takeover template](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/takeovers/aws-bucket-takeover.yaml) explicitly negates findings that have amazonaws.com in the URL.  This seems like an oversight, but maybe it was done for tuning, I'm unsure.

### Nuclei Version:
v3.3.0

### Template file:
`nuclei-templates/http/takeovers/aws-bucket-takeover.yaml`

### Command to reproduce:
`nuclei -v -t ~/nuclei-templates/http/takeovers/aws-bucket-takeover.yaml -u https://fakebucketaaz1.s3.amazonaws.com`

One assumes the above command should yield a positive finding.  The bucket doesn't exist (at the time of this submission).  Note, this is an obviously overly simplified example, but it yields the behavior one would expect.  Nuclei **should** call this out as a possible dangling bucket.  Sadly it does not.

When scanning with Katana, we often find direct S3 endpoints calls, and we were expecting nuclei to call out if the referenced bucket doesn't exist.  We can create our own template for our specific use case, but figured it was at least worth mentioning here.

This behavior seems to be introduce somewhere between, https://github.com/projectdiscovery/nuclei-templates/commit/10f54bb05fa1bcdce5b83bd897067844cf5fa63a and https://github.com/projectdiscovery/nuclei-templates/commit/f7036663f087e497dd22ecedab9d84b2bd28a415.  

Again maybe this was done for turning, but the behavior seems on face value unintuitive.

**Comment by princechaddha** [comment]
Hi @lstatro, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project. The team is looking into it.

**Comment by princechaddha** [comment]
@lstatro Apologies for the delay. The template above is specifically designed for subdomain takeovers, which is why we’ve included Host != ip along with amazonaws as a negative, to ensure the presence of a subdomain for takeover. You’re right that with Katana, there might be instances where buckets are misconfigured or not created, but this template focuses primarily on subdomain takeovers. We can certainly create a separate template for that. If you feel otherwise, please feel free to reopen the issue
