### ISSUE TITLE
SVN configuration leak template underreporting

### ISSUE THREAD

**Issue by seeblog** [projectdiscovery/nuclei-templates#10344]
### Nuclei Version:

Current nuclei version: v3.3.0 (latest)
Current nuclei-templates version: v9.9.1 (latest)

### Template file:

http/exposures/configs/exposed-svn.yaml

In the real Internet environment, a large number of underreporting was found. The rules were too strict. The simple modification is as follows

[exposed-svn.txt](https://github.com/user-attachments/files/16325536/exposed-svn.txt)

**Comment by princechaddha** [comment]
Hi @seeblog, Thank you for taking the time to create this issue and for contributing to this project 🍻

I have updated the regex in the template. However, removing the text/plain header might result in many false positives. If you encounter any false negatives due to the header removal, please let us know. Thank you.
