### ISSUE TITLE
[Feature] Bring back the all in one takeover template

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#1145]
What used to be 1 request to detect 50 takeovers now it's 50 requests to detect 50 takeovers because there is an individual template for each one.

Is it possible to bring that back? and maybe have that one and the individual ones.

**Comment by ehsandeep** [comment]
@marcelo321 not sure if you missed the blogpost https://blog.projectdiscovery.io/nuclei-v2-3-0-release/, since releasing of v2.3.0 nuclei supports request clustering that makes single GET request for all the templates having same PATH, like this, so it doesn't matter how many templates you run, if the paths are same, it will only make one request, if you running older version of nuclei, make sure to use the latest one [v.2.3.2](https://github.com/projectdiscovery/nuclei/releases/tag/v2.3.2). 

To experience this behavior you can run

`echo https://example.com | nuclei -t takeovers -v` you will notice a single HTTP request for all 65 templates.

**Comment by ehsandeep** [comment]
Closing as this is not a real issue.

**Comment by marcelo321** [comment]
Oh amazing! didn't know that. Thanks for explaining.
