### ISSUE TITLE
CVE-2019-8449.yaml gives too many false positives

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei-templates#167]
Grepping for the word "users" doesn't make sense, way too many website give code 200 to that and also has the word "users" in the html code.

Can anyone take a look at this?

**Comment by bsysop** [comment]
Wow, this is very... risky!

I will propose a fix.

**Comment by bsysop** [comment]
I have proposed
```
{"users":{"users":
```
Not perfect, will have false positives, but we have filtered 99% of dump there, since this API response haven't very few points to regex.

https://github.com/projectdiscovery/nuclei-templates/pull/169

I have tried to pull, but have failed in indentation, since i did in browser =]

I could check tomorrow if no one finish that before.

Best regards.

**Comment by bauthard** [comment]
This has been updated here https://github.com/projectdiscovery/nuclei-templates/commit/14494ba4d3fa32ef4d9feb38de0182efa5be9b9b, @bsysop thank you for the PR, that error was not related to your PR, so I've updated the templates with yours.

**Comment by bsysop** [comment]
Thank you @bauthard 🤟🏻
