### ISSUE TITLE
False positive in template due to matchers conditon being OR by default instead of AND

### ISSUE THREAD

**Issue by Ice3man543** [projectdiscovery/nuclei-templates#220]
https://github.com/projectdiscovery/nuclei-templates/blob/master/cves/CVE-2020-5284.yaml

**Comment by Ice3man543** [comment]
https://github.com/projectdiscovery/nuclei-templates/blob/master/files/elasticsearch.yaml

Above both have same root cause, a matcher with condition of status = 200. We need to fix the templates and mention matchers are by default OR.

**Comment by dwisiswant0** [comment]
I think it has been fixed on https://github.com/projectdiscovery/nuclei/pull/125.

**Comment by bauthard** [comment]
@dwisiswant0 it's the opposite case, the default behavior should be OR, but due to bug it used to be worked as AND which got fixed at projectdiscovery/nuclei#125, so few templates which were working fine because of AND behavioral as default in the past, after fix they are behaving as OR so the false positive, hence I will update few of them.

**Comment by Ice3man543** [comment]
Done!
