### ISSUE TITLE
False-positive CVE-2020-13379

### ISSUE THREAD

**Issue by dwisiswant0** [projectdiscovery/nuclei-templates#331]
Hey, `CVE-2020-13379.yaml` is giving a lots of false-positive results.

![Screenshot_2020-08-20_20-25-22](https://user-images.githubusercontent.com/25837540/90775852-8bfa0400-e323-11ea-8a8e-9f42d576f7d9.png)

@Pxmme why did you put `502` status code? If I look at the code, it returns **500** & `image/jpeg` as content-type.

Ref: -
https://github.com/grafana/grafana/blob/78febbbeef1f23ccbb88c2bd3acd2e9c2011e02a/pkg/api/avatar/avatar.go#L90;L115

**Comment by bauthard** [comment]
@Pxmme Can you please confirm this?

**Comment by dwisiswant0** [comment]
Should I?

**Comment by Pxmme** [comment]
Hey @bauthard and @dwisiswant0,

Very sorry for the delay here. I'm available now.

@dwisiswant0 I'm running this template daily against ~250,000 hosts without getting a single false positive 😮 would you mind sharing your targets via PMs on Discord? If so, feel free to add me: `Pomme#4172`

I tested this DoS against my own Grafana instance which was vulnerable at the time and I got HTTP 502 responses which is why I made this template like this, not worrying about the content-type or anything: 502 is odd enough by itself and should avoid any false positive AFAIK.

Cheers,
@Pxmme
