### ISSUE TITLE
False negative on multiples SSRF templates

### ISSUE THREAD

**Issue by akincibor** [projectdiscovery/nuclei-templates#4669]
### Nuclei Version:

Latest

### Template file:

- [x] interactsh-server.yaml
- [x] CVE-2021-27748.yaml
- [x] CVE-2021-22873.yaml
- [x] CVE-2021-22054.yaml

This is due to the matcher that check only for : `<h1> Interactsh Server </h1>`.

As you can see below, I'm getting a false negative.

<img width="569" alt="Capture d’écran 2022-06-26 à 02 11 34" src="https://user-images.githubusercontent.com/99909324/175794533-bff93064-f47f-46d5-8789-dbf6cc36fc82.png">

### Fix

Add also : `<h1> Interactsh Server <\/h1>`

**Comment by princechaddha** [comment]
Hi @akincibor, thank you for taking the time to create this issue and contributing to this project 🍻

Seeing the above screenshot, it appears that the host does not host interachsh server. This issue is not a false negative, but we are still enhancing the matchers for such templates.

Would it be possible for you to share the IP of the above host on Discord via DM for the team to verify?
