### ISSUE TITLE
[Bug] CVE-2020-7961 not working correctly

### ISSUE THREAD

**Issue by pdelteil** [projectdiscovery/nuclei-templates#545]
**Nuclei version**

```
v2.1.1
```

**Nuclei template version**

```
NA
```

**Describe the bug**
This is the output of the template (WARNING)

`[WRN] [cve-2020-7961] Could not execute step: parse "https://gea.sfo2.cdn.digitaloceanspaces.com:port/api/jsonws/invoke": invalid port ":port" after host`

The template is not correctly using the port values defined in the code (80, 443, 8080). I received this error in all the targets I was using. 

**Commands to reproduce**

```
nuclei -t CVE-2020-7961.yaml -target https://gea.sfo2.cdn.digitaloceanspaces.com
```

**Comment by bauthard** [comment]
Hi @pdelteil, 

`WRN` is not an error or issue, and you don't need to use `-v` flag as it will include success and failed request both, failed request doesn't mean it's not working, it only means that request got failed due to port is not open or not reachable.

You can read this https://github.com/projectdiscovery/nuclei/issues/339#issuecomment-703413654 for more details.

**Comment by pdelteil** [comment]
You are right. Should I used debug instead of verbose.
