### ISSUE TITLE
Wrong behaviour jsf-detection.yaml - host-redirect failed

### ISSUE THREAD

**Issue by niranc** [projectdiscovery/nuclei-templates#5998]
### Nuclei Version:

Current Version: 2.7.8

### Template file:

Wrong behaviour for template jsf-detection.yaml

### Command to reproduce:

"host-redirects" doesn't redirect requests, only "redirects" gives me valid results. 

Maybe "max-redirects" feature doesn't work for "host-redirects: true" ?

**Comment by princechaddha** [comment]
Hi @niranc, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

Both `host-redirects` and `redirects` works fine with `max-redirects`. It seems like the host on which you are running the template is redirecting to another host which is why it is not working with `host-redirects`.
