### ISSUE TITLE
xff-403-bypass false positive

### ISSUE THREAD

**Issue by fuomag9** [projectdiscovery/nuclei-templates#6306]
If the website returns 404 on `/test.txt` due to `file not found` (indipendently on `X-Forwarded-For` headers) but does not let someone access the entire website when an endpoint matches, the plugin will report that there's a 403 bypass incorrectly  

### Nuclei Version: 
2.7.9

### Template file: 
xff-403-bypass

### Command to reproduce:

`nuclei -u yourwebsite.com`

**Comment by princechaddha** [comment]
Hi @fuomag9, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to the project 🍻

The templates you have suggested may not be suitable for the public repository. To verify the accessibility of a specific endpoint using X-Forwarded-For, we need to be aware of that endpoint, which can vary from host to host. However, you can create a template for your use case by providing the known endpoints through a variable.

If you need any help with that you can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

**Comment by wesamlibya** [comment]
**done******
