### ISSUE TITLE
CVE-2021-44228 generates false positives when scanning multiple hosts

### ISSUE THREAD

**Issue by antisec135** [projectdiscovery/nuclei-templates#7020]
nuclei reported the wrong vulnerable host when I scanned multiple APIs concurrently. I feel like we need to add a hostname identifier to this template so we can identify the host on a concurrent scan.

### Nuclei Version:

Using Nuclei Engine 2.9.0

### Template file:

cves/2021/CVE-2021-44228.yaml

### Command to reproduce:

nuclei -l routes.txt -t nuclei-templates/cves/2021/CVE-2021-44228.yaml -o nuclei_rce.json -json

**Comment by princechaddha** [comment]
Hi @antisec135, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

As per the community's suggestion, we have updated the detection mechanism to verify if the request has been analyzed by log4j, which should resolve the issue [#7098](https://github.com/projectdiscovery/nuclei-templates/pull/7098).
