### ISSUE TITLE
CVE-2020-13167 False Positive (and extra possible issue)

### ISSUE THREAD

**Issue by DShelef** [projectdiscovery/nuclei-templates#7624]
### Nuclei Version:
v2.9.4

### Template file:
`http/cves/2020/CVE-2020-13167`

### Anything else:
If a website has the keyword `nonexistent` in its default/404 response the issue would be falsely detected.
In my particular case, a website included a script tag to `nonexistent.js` (surprise surprise, it doesn't exist).

P.S. Since the keyword is hard-coded, doesn't it mean the issue would be detected even if I fix the issue as long as the file created on the last detection wasn't removed?
Consider adding some random string or date-time to the content of the file that is created.

**Comment by Bobby-Firmino** [comment]
@DhiyaneshGeek Any updates here?

**Comment by DhiyaneshGeek** [comment]
Hi @DShelef , we have added `defcon31` label will be tracked

**Comment by princechaddha** [comment]
Hello @DShelef, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to the project 🍻

The template has been updated let me know if it looks good. You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again cc @Bobby-Firmino
