### ISSUE TITLE
Giving false positives when using -fr for RXSS fuzzing

### ISSUE THREAD

**Issue by oldDuDe124** [projectdiscovery/nuclei-templates#7788]
hi im trying to fuzz for reflected xss and i wanna use -fr swtich in case of any redirection to check for any reflection that may occur in the redirected page but sometimes when there is a redirection in the given urls , nuclei starts to give me some false postives and i can't figure out what i'm doing wrong here , i do wanna use -fr cause i have had some success with it but these false positives are driving me crazy!!
i'm using nuclei and nuclei templates of the latest version and here is the template( just a simple template , nothing fancy):

id: xss

info:
  name: xss detection
  author: nobody
  severity: high
  tags: hunt
requests:
  - method: GET
    path:
      - '{{BaseURL}}/%3Cfoo%22%3E'
      - '{{BaseURL}}?url=%3Cfoo%22%3E'
      - '{{BaseURL}}?callback=%3Cfoo%22%3E'
      - '{{BaseURL}}?return=%3Cfoo%22%3E'
      - '{{BaseURL}}?next=%3Cfoo%22%3E'
      - '{{BaseURL}}?redir=%3Cfoo%22%3E'
      - '{{BaseURL}}?rurl=%3Cfoo%22%3E'
      - '{{BaseURL}}?target=%3Cfoo%22%3E'
      - '{{BaseURL}}?link=%3Cfoo%22%3E'
      - '{{BaseURL}}?ref=%3Cfoo%22%3E'
      - '{{BaseURL}}?search=%3Cfoo%22%3E'
      - '{{BaseURL}}?from=%3Cfoo%22%3E'
      - '{{BaseURL}}?to=%3Cfoo%22%3E'
      - '{{BaseURL}}?id=%3Cfoo%22%3E'
    matchers-condition: and
    matchers:
     - type: word
       part: body
       condition: or
       words:
         - '<foo">'
         - '<foo>'
         - 'foo"'
         - '<foo"'

**Comment by princechaddha** [comment]
Hi @oldDuDe124, The response time to this issue was much longer than usual. It seems that the false positive occurs because, at times on the redirection page, the payload like <foo"> is being reflected before the redirection takes place. However, this alone doesn't confirm the presence of a vulnerability. In this particular case, the false positive is a result of weak matchers in the template. Detecting XSS is not a straightforward process as it relies heavily on the context in which the payload is being reflected. Feel free to create another issue if you come across any templates that produce false positive or negative results in this repository.

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors stay updated with the latest developments and ask for help in writing templates and improving matcher.
