### ISSUE TITLE
Remove evil.com and change it to example.com for identifying open redirect issues

### ISSUE THREAD

**Issue by 0xdln1** [projectdiscovery/nuclei-templates#7916]
https://evil.com returns a 404 , A better and stable matcher for open redirect would be example.com 

Affected Template: https://github.com/projectdiscovery/nuclei-templates/blob/main/headless/headless-open-redirect.yaml

<img width="387" alt="Screenshot 2023-08-12 at 4 15 02 PM" src="https://github.com/projectdiscovery/nuclei-templates/assets/83292788/8639d554-12de-4f26-abf1-1687364553c0">

**Comment by princechaddha** [comment]
Hi @0xdln1, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

We have observed many hosts redirecting to example.com for testing without being vulnerable to open redirects. We have updated the template with the URL of our interact server. Thank you once again.
