### ISSUE TITLE
False positive with newly added flir-ax8-rce.yaml template

### ISSUE THREAD

**Issue by tarunkant** [projectdiscovery/nuclei-templates#8005]
### Nuclei Version:
v2.9.10

### Template file:

http/vulnerabilities/other/flir-ax8-rce.yaml

### Description:

It is generating false positives due to weak matcher condition. Having a "success" string with 200 status code is not enough to produce a true positive. It is suggested to strict the matcher condition with specific details to Flir-ax8 or extractors should be there.

**Comment by DhiyaneshGeek** [comment]
Hey @tarunkant Is it possible share the FP target 

Feel Free to join our discord server https://discord.com/invite/projectdiscovery

**Comment by DhiyaneshGeek** [comment]
Hi @tarunkant i have fixed the weak matcher and raised a PR #8007 

Let me know if it fixes the FP 

Thanks

**Comment by tarunkant** [comment]
@DhiyaneshGeek, Yes the PR perfectly works. Thanks!

**Comment by princechaddha** [comment]
Hi @tarunkant, Thank you for taking the time to create this issue and for contributing to this project 🍻

You can join our [Discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. We would also like to reward you with our swag as a token of appreciation for your contribution. Could you please DM me on Discord so that I can share the details? Thank you once again!

**Comment by tarunkant** [comment]
Hello @princechaddha, Thank you and I really appreciate it. I DM'ed you in Discord.
