### ISSUE TITLE
WPS Office Rce

### ISSUE THREAD

**Issue by whereveryouare666** [projectdiscovery/nuclei-templates#8093]
### Template for?

WPS Office RCE

### Details:

PoC
https://github.com/ba0gu0/wps-rce

**Comment by princechaddha** [comment]
Hi @whereveryouare666, Thank you for taking the time to create this issue and for contributing to this project 🍻

For this template, we need to purchase the `****wps.cn` domain and manually set up a CDN and an nginx proxy. This setup should be validated manually. This is why I am closing this issue. Please let me know if you think otherwise. Feel free to request templates for other CVEs.

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again
