### ISSUE TITLE
Home router KEO wireless KLR 300N manager panel

### ISSUE THREAD

**Issue by andreluna** [projectdiscovery/nuclei-templates#8138]
### Template Information:

- Description:
    - Home router wireless KLR 300N without login/password
 
- References:
    - http://www.keo.com.br/produtos/roteador-klr-300n
    - http://www.keo.com.br/wp-content/uploads/2017/09/Manual_KLR_300N_03-17_site.pdf 

### Nuclei Template:

```
id: keo-router-klr300n

info:
  name: Home router wireless KLR 300N manager panel
  author: andreluna
  description: Home router wireless KLR 300N without login/password
  severity: medium
  reference:
    - http://www.keo.com.br/produtos/roteador-klr-300n
    - http://www.keo.com.br/wp-content/uploads/2017/09/Manual_KLR_300N_03-17_site.pdf
  metadata:
    max-request: 1
    shodan-query: html:"def_wirelesspassword"
  tags: panel

http:
  - method: GET
    path:
      - "{{BaseURL}}/"

    redirects: true
    max-redirects: 1
  
    matchers-condition: and
    matchers:
      - type: word
        words:
          - "<title>Roteador Wireless KLR 300N</title>"
          - "def_wirelesspassword"
        part: body
        condition: and 

      - type: status
        status:
          - 200
```

- Results:
```
[keo-router-klr300n] [http] [medium] http://187.[redacted]/index.asp 
```

**Comment by pussycat0x** [comment]
Hi @andreluna  Thank you for sharing this template with the community and for your contribution to this project. Closing this PR since we already have a template for Installation page [http/misconfiguration/installer/klr300n-installer.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/installer/klr300n-installer.yaml)
