### ISSUE TITLE
`cves.json` does not contains CVEs from network protocol

### ISSUE THREAD

**Issue by iamtimroberts** [projectdiscovery/nuclei-templates#8172]
### Issue description:
CVE-2023-33246 has a template in [network/cves/2023/CVE-2023-33246](https://github.com/projectdiscovery/nuclei-templates/blob/main/network/cves/2023/CVE-2023-33246.yaml) but the CVE/template isn't listed in [cves.json](https://github.com/projectdiscovery/nuclei-templates/blob/main/cves.json)

**Comment by princechaddha** [comment]
Hi @iamtimroberts, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

It appears that the GitHub action is only adding CVEs under `http/cves/`, not under `network/cves/`. The team will update it shortly.

**Comment by ehsandeep** [comment]
Workflow to fix: https://github.com/projectdiscovery/nuclei-templates/blob/9d0fa3af3285e909fbd7b03f6112f320b4dc3a90/.github/workflows/cve2json.yml#L27C1-L28C1

**Comment by parthmalhotra** [comment]
Hey @iamtimroberts, This is now fixed.
