### ISSUE TITLE
can anyone make Ghostcat: CVE-2020-1938 template

### ISSUE THREAD

**Issue by x3n0nme** [projectdiscovery/nuclei-templates#82]

**Comment by Ice3man543** [comment]
Here is an exploit for the said CVE - [https://github.com/xindongzhuaizhuai/CVE-2020-1938/blob/master/CVE-2020-1938.py](https://github.com/xindongzhuaizhuai/CVE-2020-1938/blob/master/CVE-2020-1938.py). However, adding it to nuclei i'm afraid is not an option for detection as of now since we don't have any mechanism for sending raw tcp requests.

**Comment by bauthard** [comment]
Closing this as per the above comment.
