### ISSUE TITLE
CITRIX EXPLOIT 2023

### ISSUE THREAD

**Issue by whereveryouare666** [projectdiscovery/nuclei-templates#8462]
### Template for?

CVE-2023-3519 and CVE-2023-4966

### Details:

PoC Exploit for CVE-2023-3519
https://github.com/assetnote/exploits/tree/main/citrix/CVE-2023-3519

PoC Exploit for CVE-2023-4966
https://github.com/assetnote/exploits/tree/main/citrix/CVE-2023-4966

**Comment by princechaddha** [comment]
Hi @whereveryouare666, Thank you for taking the time to create this issue and for contributing to this project 🍻

We have added `CVE-2023-4966` [here](https://github.com/projectdiscovery/nuclei-templates/pulls?q=is%3Apr+CVE-2023-4966+is%3Aclosed) and have an open PR for CVE-2023-3519 [here](https://github.com/projectdiscovery/nuclei-templates/pull/7734/files) but it is blocked because the POC can result in dos.
