### ISSUE TITLE
web2py OS Command Injection

### ISSUE THREAD

**Issue by whereveryouare666** [projectdiscovery/nuclei-templates#8589]
### Template for?

CVE-2023-45158

### Details:

PoC
https://github.com/Evan-Zhangyf/CVE-2023-45158

**Comment by princechaddha** [comment]
@whereveryouare666, The CVE you shared applies when the product is configured to use notifySendHandler for logging. The reference you provided is a demo of a vulnerable web application, so writing a Nuclei template for it isn't feasible, as we're unaware of the vulnerable endpoints and parameters, which in this case is /hack?msg=. However, we could possibly write a [fuzzing template](https://github.com/projectdiscovery/fuzzing-templates) for it. Feel free to reopen the issue if you feel otherwise.
