### ISSUE TITLE
error says:  549 killed and 550 done

### ISSUE THREAD

**Issue by Dark-Aura** [projectdiscovery/nuclei-templates#8591]
### Issue description:
Recently for the past 15 days I'm facing this issue while the Nuclei is running all of a sudden this error appears and ends the scanning 
error message: [1]    549 killed     nuclei -l 4.11.txt -eid  -nmhe  |        550 done       tee nuc_44.11.txt
![nuclei](https://github.com/projectdiscovery/nuclei-templates/assets/65353593/0296a26e-a82b-425a-8c58-87c6aa613129)

### Anything else:
I'm attaching the Screenshot for you to take a look at.

**Comment by princechaddha** [comment]
Hi @Dark-Aura, The response time to this issue was much longer than usual. It seems to be a memory issue, as you are running over 10,000 templates on 5,374 targets from a single machine. To handle such a large scan, you will need to run a distributed scan. This issue is not a bug in Nuclei. Feel free to reopen the issue if you have any further queries

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again
