### ISSUE TITLE
False positives of two templates on phpinfo()

### ISSUE THREAD

**Issue by kazet** [projectdiscovery/nuclei-templates#8657]
### Nuclei Version:

v3.0.4

### Template file:

http/cnvd/2020/CNVD-2020-23735.yaml
http/vulnerabilities/other/ecshop-sqli.yaml

### Command to reproduce:

~/go/bin/nuclei -t http/cnvd/2020/CNVD-2020-23735.yaml  -t http/vulnerabilities/other/ecshop-sqli.yaml -u https://experiment.kazet.cc/phpinfo.php

### Anything else:
https://experiment.kazet.cc/phpinfo.php is a site with `<?php phpinfo(); ?>`

**Comment by princechaddha** [comment]
Hi @kazet, The response time to this issue was much longer than usual. Thank you for taking the time to create this issue and for contributing to this project 🍻

Although we have updated the templates, I would like to mention that users are expected to provide a URL as the target, rather than a complete endpoint like `https://experiment.kazet.cc/phpinfo.php`. Thanks once again.

**Comment by kazet** [comment]
I understand that users are expected to provide a root URL, but when performing scanning as CERT PL we observed some sites that returned phpinfo() on a root URL of e.g. a test subdomain. The phpinfo.php url I provided here was just for testing.
