### ISSUE TITLE
Apache Struts RCE Vulnerability

### ISSUE THREAD

**Issue by whereveryouare666** [projectdiscovery/nuclei-templates#8840]
### Template for?

CVE-2023-5016

### Details:
PoC
https://github.com/jakabakos/CVE-2023-50164-Apache-Struts-RCE

**Comment by princechaddha** [comment]
Hi @whereveryouare666, the response time to this issue was much longer than usual. Thank you for taking the time to create this issue. The reference you have shared includes a demo app which showcases the CVE, but that upload endpoint will not be present in real-world applications.

We will be able to write a [fuzzing template](https://github.com/projectdiscovery/fuzzing-templates) for it once we enhance the fuzzing in Nuclei, which is a work in progress. Therefore, I am closing this issue.

Feel free to reopen it if you think otherwise. Thanks!
