### ISSUE TITLE
KEV Tag Assignment

### ISSUE THREAD

**Issue by rxerium** [projectdiscovery/nuclei-templates#9034]
Hi there,

Over the past few months I've noticed several templates not being tagged as `kev` correctly. A suggestion for fixing this could be to incorporate a workflow (gh action) that grabs the CISA KEV and checks to see which templates are in the kev and which ones are not. Those that are, a new PR can be created with the addition of the KEV tag and can be merged accordingly. Just out of curiosity how do currently manage this? 

Thanks

Rishi

**Comment by princechaddha** [comment]
We have been using the [Templateman](https://github.com/projectdiscovery/nuclei-templates/actions/workflows/templateman.yml) workflow to update the KEV tags in the templates, but it was disabled due to some changes it made in the templates. We have since reverted those changes and re-enabled the workflow. I just reran the workflow as the bug has been fixed.

Please let me know if you can find CVEs that are KEVs but not assigned a KEV tag

**Comment by princechaddha** [comment]
There are still some issues with the workflow. I will provide an update on this issue when it's fixed

**Comment by princechaddha** [comment]
@rxerium The tags have been updated in this commit: [GitHub Commit Link](https://github.com/projectdiscovery/nuclei-templates/commit/5d263425e68e6ecfa2668dd68a471180ec3be540).

**Comment by princechaddha** [comment]
Closing this issue. Feel free to reopen if you come across a CVE with a missing KEV tag
