### ISSUE TITLE
Strict matchers changes

### ISSUE THREAD

**Issue by rxerium** [projectdiscovery/nuclei-templates#9412]
Hi there,

I noticed 2 DNS templates were added to the `.nuclei-ignore` file:
```
  - dns/soa-detect.yaml
  - dns/txt-service-detect.yaml
```

I understand templates that are added to the ignore file could generate FPs as they have "weak matchers". Could you let me know how I could potentially strengthen the matchers for these templates? Open to suggestions 😊

Many thanks,

Rishi

**Comment by princechaddha** [comment]
Hello @rxerium,

I should have updated you on this change earlier. We have temporarily restricted these templates, although they don't use weak matchers, they generate a large number of results for each subdomains. We are waiting for an update on the Nuclei engine to enable recommended scans to run by default, and users can run DNS profiles for these scans. This is because they might not be useful for all use cases and could overwhelm users with the volume of info results. Additionally, we have removed phishing templates from the ignore list, and they now run on the default scan.

**Comment by rxerium** [comment]
ahh that makes sense thanks @princechaddha and looking forward to the new update!
